version: "3.7"
services:
  web1:
    build: ./quote_gen
    # container_name: quote-gen-container
    ports:
      - "5000:5000"
    volumes:
      - web_data:/etc/data
  web2:
    build: ./quote_disp
    # container_name: quote-disp-container
    ports:
      - "5001:5001"
    volumes:
      - web_data:/var/www/html
    depends_on:
      - web1
  
volumes:
    web_data: